### ISSUE TITLE
Make language mandatory only for public bookmarks

### ISSUE THREAD

**Issue by adrianmatei-me** [BookmarksDev/bookmarks.dev#38]

**Comment by vbvjain** [comment]
Hi, Can you describe this issue a little bit?  According to my observation, when I create a bookmark, "save bookmark" button is disabled when the "make public" checkbox is unchecked. When the checkbox is checked then "save bookmark" button is enabled and I can save the bookmark.

**Comment by adrianmatei-me** [comment]
Hi @vbvjain ,

The "Save bookmark" is enabled once you fill in the required fields (**location**, **title** and **tags**) , it hast nothing to do with making public - if you decide to make the bookmark public, only then you need to give the language of the article (video) as input...

**Comment by adrianmatei-me** [comment]
Forgot to mention, this issue is already implemented and in production

**Comment by vbvjain** [comment]
@adrianmatei-me okay.
