### ISSUE TITLE
Keycloak token expiration too low.

### ISSUE THREAD

**Issue by samuelabreu** [BookmarksDev/bookmarks.dev#43]
In https://www.bookmarks.dev/ i have to enter my credentials frequently, checking browser console i saw a 600 seconds token expiration time, maybe a option to set this timer for an account?

**Comment by adrianmatei-me** [comment]
Hey Samuel, by frequently how often do you mean?  (The session is currently set to 5 days, I could increase that). Did you also use the "Remember me" function?

The 600 is the access token expiration time, which is supposed to be short and is supposed to be automatically when you use the application...

**Comment by samuelabreu** [comment]
My mistake, i remember was testing a few things and had to login again after 10 minutes, but i tested now and didn't need it.

Thanks
